
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0.3.4
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema*.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "app/channels/**/*"
    - "config/**/*"
    - "config.ru"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "test/**/*"
    - "spec/**/*"
    - "app/helpers/admin/*_helper.rb"require 'rails_helper'
